# theme.toml template for a Hugo theme
# See https://github.com/spf13/hugoThemes#themetoml for an example

name = "origin"
license = "MIT"
licenselink = "https://github.com/DanielMuller/hugo-theme-origin/blob/master/LICENSE.md"
description = ""
homepage = "https://github.com/DanielMuller/hugo-theme-origin"
tags = ["blog"]
features = ["blog"]
min_version = 0.20

[author]
  name = "Daniel Muller"
  homepage = "https://daniel.ctrlaltdel.ch/"

# If porting an existing theme
[original]
  name = "Origin for Wordpress"
  homepage = "https://alienwp.com/themes/origin/"
